config/routes.rb
OnlinePatient::Application.routes.draw do

	root 'static_pages#home'
  resources :departments
  resources :doctors, :only=>[:new, :create, :show]
  get 'Sign Up', to: 'doctors#search', as: :signup
  post 'doctors/uptodate'
  resources :sessions, :only=>[:new, :create, :destroy]
  get 'signin', to: 'sessions#new', as: :signin
  get 'signout', to:'sessions#destroy', as: :signout
  resources :patients, :only=>[:new, :create]
  resources :appointments, :only=>[:new, :create, :index, :edit, :update]

  

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

	extend SimpleCalendar
  
  has_calendar

	belongs_to :doctor, dependent: :destroy
	
	belongs_to :patients, dependent: :destroy
	
	validates :doctor_id, presence: true
	
	validates :patient_id, presence: true, uniqueness: {scope: [:appointment_date, :appointment_time], message: " already have an appointment at that time. So please choose some other time. Thank you."}
	
	validates :appointment_date, presence: true, uniqueness: {scope: [:patient_id, :doctor_id]}

	validates :appointment_time, presence: true, uniqueness: {scope: [:appointment_date, :doctor_id], message: " is not available.. Sorry"}

end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :doctors
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
	
	belongs_to :department, dependent: :destroy
	
	has_many :appointments

	has_secure_password validations: false

	validates :name, presence: true, on: :create
	
	validates :age, presence: true, on: :create
	
	validates :sex, presence: true, on: :create
	
end

app/models/patient.rb
class Patient < ActiveRecord::Base

	has_many :appointments
	
	validates :fname, :lname, :age, :sex, :street, :city, :state, :email, presence: true
	
	validates :email, uniqueness: true
	
	validates :age, numericality: { only_integer: true }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_doctor
  
  private
  	
  	def current_doctor
  		@current_doctor ||= Doctor.find(session[:doctor]) if session[:doctor]
  	end	
  	
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

	helper_method :find_patient_name
	
	helper_method :find_appointment_time
	
	helper_method :find_doctor

	def index
		@date = params[:dated]
		@patients = current_doctor.appointments.where(appointment_date: "#{@date}")
	end

	def new
		@appointment = Appointment.new
	end
	
	def create
		@appointment = Appointment.new(appointment_params)
		if @appointment.save
			flash[:success] = "Successfully you have scheduled an appointment on #{@appointment.appointment_date} at #{@appointment.appointment_time}"
			redirect_to root_url
		else
			render :new
		end
	end
	
	def edit
		@patient = Patient.find(params[:id])
		@appointment = @patient.appointments.find_by appointment_date: "#{Date.today}"
		@app = @patient.appointments
	end
	
	def update
		@appointment = Appointment.find(params[:id])
		if @appointment.update_attributes(appointment_params)
			redirect_to appointments_path
		else
			render :edit
		end		
	end
		
	private
		
		def appointment_params
			params.require(:appointment).permit(:department_id, :doctor_id, :patient_id, :appointment_date, :appointment_time, :report, :complete)
		end
		
		def find_patient_name(name)
			p = Patient.find("#{name}")
			p.fname + " " + p.lname
		end
		
		def find_appointment_time(patient_id, appointment_date)
			p = Patient.find("#{patient_id}")
			a = p.appointments.find_by appointment_date: "#{appointment_date}"
			a.appointment_time
		end

		def find_doctor(id)
			doc = Doctor.find(id)
			doc.name
		end

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

	def index
		@departments = Department.all
	end

	def show
		@department = Department.find(params[:id])
	end

	def new
		@department = Department.new
	end

	def create
		@department = Department.new(department_params)
		if @department.save
			redirect_to root_url
		else
			redirect_to root_url
		end	
	end

	private
		def department_params
			params.require(:department).permit(:name)
		end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

	rescue_from ActiveRecord::RecordNotFound, with: :show_error

	def new
		@department = Department.find(params[:id])
		@doctor = Doctor.new
	end

	def create 
		@doctor = Doctor.new(doctor_params)
		if @doctor.save
			flash[:success] = "#{@doctor.name} has been added and his/her id is #{@doctor.id}"
			redirect_to root_url
		else
			render :new, locals: {:@department=>Department.find(@doctor.department_id)}
		end
	end
	
	def show
		@doctor = Doctor.find(params[:id])
	end

	def uptodate
		@doctor = Doctor.find("#{params[:id]}")
		if @doctor.name == "#{params[:name]}"
			@doctor.password = "#{params[:password]}"
			@doctor.password_confirmation = "#{params[:password_confirmation]}"
			if @doctor.update(doctor_params)
				flash[:success] = "Successfully signed up" 
				redirect_to root_url
			end
		else
			flash.now[:error] = "Error. Id and Name mismatch"
			render :search
		end
	end
	
	private

		def doctor_params
			params.fetch(:doctor, {}).permit(:name, :age, :sex, :experience, :qualification, :department_id, :password, :password_confirmation)
		end

  	def show_error
  		flash.now[:error] = "Invalid id"
  		render :search
  	end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

	def new
		@patient = Patient.new
	end
	
	def create
		@patient = Patient.new(patient_params)
		if @patient.save
			flash[:success] = "#{@patient.fname} #{@patient.lname} has successfully registered. Your Patient id is #{@patient.id}"
			redirect_to root_url
		else
			render :new
		end		 
	end
	
	private
		
		def patient_params
			params.fetch(:patient, {}).permit(:fname, :lname, :age, :sex, :street, :city, :state, :email)
		end
	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	rescue_from ActiveRecord::RecordNotFound, with: :show_error

	def create
		@doctor = Doctor.find(params[:id])
		if @doctor && @doctor.authenticate(params[:password])
			flash[:success] = "Successfully logged in"
			session[:doctor] = @doctor.id
			redirect_to root_url
		else
			show_error
		end		
	end

	def destroy
		session[:doctor] = nil
		flash[:success] = "Successfully logged out."
		redirect_to root_url
	end
	
	private
	
  	def show_error
  		flash.now[:error] = "Invalid id/password"
  		render :new
  	end
	
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/views/appointments/edit.html.erb
<table align="center">
	<tr><td>Name: </td>
			<td><%= find_patient_name(@appointment.patient_id) %></td></tr>
	<tr><td>Age: </td>
			<td><%= Patient.find(@appointment.patient_id).age %></td></tr>		
	<tr><td>Sex: </td>
			<td><%= Patient.find(@appointment.patient_id).sex %></td></tr>
</table>
<table align="center">
<%= form_for @appointment do |f| %>
	<th><%= f.label "Report" %></th>
	<tr><td><%= f.text_area :report %></td></tr>
	<%= f.hidden_field :complete, {:value=>1} %>
	<tr><td><%= f.submit "Submit" %></td></tr>
<% end %>
</table>
<p align="left">Previous reports</p>
<table align="left">
<% @app.each do |a| %>
	<% if a.id == @appointment.id %>
	<% else %>
	<tr><td><%= a.report %></td>
	<td> by Dr. <%= find_doctor(a.doctor_id) %>,</td>
	<td> <small>Date: <%= a.appointment_date %></small></td></tr>
	<% end %>
<% end %>	
</table>

app/views/appointments/index.html.erb
<div> Appointments </div>
<%= @date %><br/>
<% if @patients.any? %>
	<table align="center">
		<% @patients.each do |p| %>
			<tr>
				<td>
					<%= link_to find_patient_name(p.patient_id), edit_appointment_path(id: "#{p.patient_id}") %>
				</td>
				<td>
					<%= find_appointment_time(p.patient_id, @date) %>
				</td>
				<td>
					<% if p.complete %>
						, Done
					<% end %>
				</td>
			</tr>
		<% end %>
	</table>
<% else %>
	<p> No Patients scheduled </p>
<% end %>

app/views/appointments/new.html.erb
<h1>Appointment Form</h1>
<% if @appointment.errors.any? %>
        The form contains <%= pluralize(@appointment.errors.count, "error") %>.
  <div id="errors">
    <ul>
    	<% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    	<% end %>
    </ul>
  </div>  
<% end %>

<%= form_for @appointment do |f| %>
	<table align='center'>	
	<tr>
		<td>
			<%= f.label "Patient Id" %>
		</td>
		<td>
			<%= f.text_field :patient_id %>
		</td>
	</tr>
	<tr>
		<td>
			<%= f.label "Department" %>
		</td>
		<td> 
			<%= collection_select(:doctor, :department_id, Department.all, :id, :name, {:prompt => "Select Department"}) %>
		</td>	
	</tr>
	<tr>
		<td>
			<%= f.label "Doctor :" %>
		</td>
		<td>
		<%= f.grouped_collection_select(:doctor_id, Department.order(:name), :doctors, :name, :id, :name, {prompt: "Select doctor"}, {:id=>"doctor_select"}) %>
		</td>
	</tr>
	<tr>
		<td>
			<%= f.label "Date" %>
		</td>
		<td>
			<%= f.text_field :appointment_date %> 
		</td>
	</tr>
	<tr id='appointment_time'>
		<td>
			<%= f.label "Time" %>
		</td>
		<td>
			<%= f.select(:appointment_time, [['10-10:30 AM'], ['10:30 -11 AM'], ['11-11:30 AM'], ['11:30-12 PM'], ['12-12:30 PM'], ['12:30-1 PM'], ['3-3:30 PM'], ['3:30-4:00 PM'], ['4:00-4:30 PM'], ['4:30-5 PM'], ['5-5:30 PM'], ['5:30-6 PM']]) %>
		</td>
	</tr>
	<tr>
		<td></td>
		<td>	
			<%= f.submit %>
		</td>
	</tr>		
	</table>
<% end %>

app/views/departments/index.html.erb
<% @departments.each do |dept| %>
	<%= link_to dept.name, dept %><br/>
<% end %>

app/views/departments/new.html.erb
<%= form_for @department do |f| %>
	<%= f.label :Name %>
	<%= f.text_field :name %>
	<%= f.submit :Submit %>
<% end %>

app/views/departments/show.html.erb
<% if @department.doctors.nil? %>
	<h1> No Doctors </h1>
<% else %>
		<p><b>Head of the Department</b></p>
		<% @department.doctors.each do |d| %>
			<% if d.admin? %>
					<%= link_to d.name, d %><br/>
			<% end %>		
		<% end %>
		<p><b>Associate Doctors</b></p>	
		<% @department.doctors.each do |d| %>
			<% if d.admin? %>
			<% else %>		
				<%=	link_to d.name, d %><br/>
			<% end %>
		<% end %>
<% end %>
<% if current_doctor %>
	<% if current_doctor.admin %>
		<%= link_to 'New', new_doctor_path(:id=>@department.id) %>
	<% end %>
<% end %>

app/views/doctors/edit.html.erb
<h1>Sign Up</h1>
<%= form_tag('/doctors/2', method: :put) do %>
	<%= label_tag("Id") %>
	<%= text_field_tag(:id) %>
	<%= label_tag("Name") %>
	<%= text_field_tag(:name) %>
	<%= label_tag("Password") %>
	<%= password_field_tag(:password) %>
	<%= label_tag(:password_confirmation, "Password Confirmation") %>
	<%= password_field_tag(:password_confirmation) %>
	<%= submit_tag("Sign Up") %>
<% end %>

app/views/doctors/new.html.erb
<div class="error">
<% if @doctor.errors.any? %>
	<p><%= @doctor.errors.count %> errors occurred</p>
	<ul>
		<% @doctor.errors.full_messages.each do |m| %>
		<li>
			<%= m %>
		</li>
		<% end %>
	</ul>
<% end %>
</div>

<%= form_for(@doctor) do |f| %>
	<%= f.label :Name %>
	<%= f.text_field :name %><br/>
	<%= f.label :Sex %>
	<%= f.text_field :sex %><br/>
	<%= f.label :Age %>
	<%= f.text_field :age %><br/>
	<%= f.hidden_field :department_id, {:value => @department.id} %>
	<%= f.label "Qualification" %>
	<%= f.text_field :qualification %><br/>
	<%= f.label "Speciality" %>
	<%= f.text_field :experience %><br/>
	<%= f.submit :Submit %>
<% end %>

app/views/doctors/search.html.erb
<h1>Sign Up</h1>
<table>
	<%= form_tag(controller: "doctors", action: "uptodate") do %>
		<tr>
			<td>
				<%= label_tag("Id") %>
			</td>
			<td>
				<%= text_field_tag(:id) %>
			</td>
		</tr>
		<tr>
			<td>
				<%= label_tag("Name") %>
			</td>
			<td>
				<%= text_field_tag(:name) %>
			</td>
		</tr>
		<tr>
			<td>
				<%= label_tag("Password") %>
			</td>
			<td>
				<%= password_field_tag(:password) %>
			</td>
		</tr>
		<tr>
			<td>
				<%= label_tag(:password_confirmation, "Password Confirmation") %>
			</td>
			<td>
				<%= password_field_tag(:password_confirmation) %>
			</td>
		</tr>
		<tr>
			<td></td>
			<td>
				<%= submit_tag("Sign Up") %>
			</td>
		</tr>
<% end %>
</table>

app/views/doctors/show.html.erb
<h2> Profile </h2>
	Name: <%= @doctor.name %><br/>
	Sex : <%= @doctor.sex %><br/>
	Qualification: <%= @doctor.qualification %><br/>
	Speciality: <%= @doctor.experience %><br/>

<%= link_to 'Back', department_path(id: "#{@doctor.department_id}") %>

app/views/layouts/_footer.html.erb
	Rails app by Sheharose Naveed Baig | 
	<%= link_to 'About Us', '#' %>| 
	<%= link_to 'Help', '#' %>

app/views/layouts/_header.html.erb
	<h2 align="center">Online Scheduler</h2>
	<ul id="sample-menu-1" class="sf-menu">
	<li>
		<%= link_to 'Home', root_url %> 
	</li>
	<li>	
		<%= link_to 'Department', departments_path %>
			<ul>
					<% depts = Department.all %>
					<% depts.each do |d| %>
						<li><%= link_to d.name, d %></li>
					<% end %>	
			</ul>
	</li>
	</ul>			
	<% if current_doctor %>
		<p> Logged in as Dr.<%= current_doctor.name %> <%= link_to 'Sign Out', signout_path %></p>
	<% else %>
		 <%= link_to 'Sign In', signin_path %>	
	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlinePatient</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
	<div id="header"> 
		<%= render 'layouts/header' %>
	</div>	
	<div class="content" %>
		<small><p id='success'><%= flash[:success] if flash[:success].present? %></p>
		<p class='error'><%= flash[:error] if flash[:error].present? %></p></small>
		<%= yield %>
	</div>
	<div id="footer">	
		<%= render 'layouts/footer' %>
	</div>
</div>
</body>
</html>

app/views/patients/new.html.erb
<h1> Registration Form</h1>
<div class="error">
<% if @patient.errors.any? %>
	<p><%= pluralize(@patient.errors.count, "error") %> occurred</p>
	<ul>
		<% @patient.errors.full_messages.each do |m| %>
		<li>
			<%= m %>
		</li>
		<% end %>
	</ul>
<% end %>
</div>
<div id="table">
<%= form_for @patient do |f| %>
 <table align='center'>
 		<tr>
 			<td>
 				<%= f.label "First Name" %>
 			</td>
 			<td>
 				<%= f.text_field :fname %>
 			</td>
 		</tr>
 		<tr>
 			<td>
 				<%= f.label "Last Name" %>
 			</td>
 			<td>
 				<%= f.text_field :lname %>
 			</td>
 		</tr>
 		<tr>
 			<td>
 				<%= f.label "age" %>
 			</td>
 			<td>
 				<%= f.text_field :age %>
 			</td>
 		</tr>
 		<tr>
 			<td>
 				<%= f.label "Sex" %>
 			</td>
 			<td>
 				<%= f.radio_button :sex, "Male" %>Male
 				<%= f.radio_button :sex, "Female" %>Female
 			</td>
 		</tr>
 		<tr>
 			<td>
 				<%= f.label "Street" %>
 			</td>
 			<td>
 				<%= f.text_field :street %>
 			</td>
 		</tr>
 		<tr>
 			<td>
 				<%= f.label "City" %>
 			</td>
 			<td>
 				<%= f.text_field :city %>
 			</td>
 		</tr>
 		<tr>
 			<td>
 				<%= f.label "State" %>
 			</td>
 			<td>
 				<%= f.text_field :state %>
 			</td>
 		</tr>
 		<tr>
 			<td>
 				<%= f.label "Email" %>
 			</td>
 			<td>
 				<%= f.text_field :email %>
 			</td>
 		</tr>
 		<tr>
 			<td>
 			</td>
 			<td>
 				<%= f.submit "Register" %>
 			</td>
 		</tr>
 	</table>
<% end %>		
</div>

app/views/static_pages/home.html.erb
<% if current_doctor %>
	<div id="calendar" align="center"><%= month_calendar do |date| %>
  	<%= link_to date.day, appointments_path(dated: date) %>
	<% end %></div>
<% else %>	
	<h1>Welcome To Online Patient Scheduler</h1>
	<h2>Schedule an <%= link_to 'Appointment', new_appointment_path %> online</h2>
	<h2> Haven't registered yet? <%= link_to 'Click Here', new_patient_path %></h2>
<% end %>